name: Build and Deploy Telegram Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tiktok-downloader-tg-bot:latest

      - name: Clean old container and image
        run: |
          docker stop tiktok-downloader-tg-bot || true
          docker rm tiktok-downloader-tg-bot || true
          docker image prune -f

      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tiktok-downloader-tg-bot:latest

      - name: Run new container
        run: |
          docker run -d \
            --name tiktok-downloader-tg-bot \
            -e TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }} \
            -e TEMP_DOWNLOAD_FOLDER=/tmp \
            -p 2001:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/tiktok-downloader-tg-bot:latest
